# Generated by Django 3.0.8 on 2020-09-22 00:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_auto_20200921_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('inicio', models.DateTimeField(default=datetime.datetime(2020, 9, 22, 0, 2, 19, 403359, tzinfo=utc), verbose_name='Início')),
                ('fim', models.DateTimeField(default=datetime.datetime(2020, 9, 22, 0, 2, 19, 403410, tzinfo=utc), verbose_name='Fim')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='OBS')),
            ],
            options={
                'db_table': 'escala',
            },
        ),
        migrations.CreateModel(
            name='ScheduleMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.Schedule')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Member')),
            ],
            options={
                'db_table': 'escala_membro',
            },
        ),
    ]
