# Generated by Django 3.0.8 on 2020-09-22 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='fim',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início'),
        ),
    ]
