# Generated by Django 3.0.8 on 2020-10-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_auto_20200921_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemember',
            name='presenca',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
