# Generated by Django 3.0.8 on 2020-08-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='UF'),
        ),
    ]
