# Generated by Django 3.0.8 on 2020-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200921_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='player_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
