# Generated by Django 3.0.8 on 2020-10-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20201001_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
