# Generated by Django 3.0.8 on 2020-09-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20200902_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, default='profile/default-user.jpg', null=True, upload_to='profile/', verbose_name='Foto de Perfil'),
        ),
    ]
