# Generated by Django 3.0.8 on 2020-09-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='categoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Categoria'),
        ),
    ]
