# Generated by Django 3.0.8 on 2020-10-02 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20201001_2222'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('message', models.TextField(null=True)),
                ('checked', models.BooleanField(default=False)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Member')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
    ]
