# Generated by Django 3.0.8 on 2020-10-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ativo'),
        ),
    ]
